apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kubernetes-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-kubernetes-app
  template:
    metadata:
      labels:
        app: my-kubernetes-app
    spec:
      containers:
      - name: my-kubernetes-app
        image: akshithapulaboyina/my-kubernetes-app:v1  # your Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
